/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'steve' at '20/11/14 21:10' with Gradle 2.1
 *
 * @author steve, @date 20/11/14 21:10
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
